# Site settings
baseurl = "http://falconridgekansas.com/"
languageCode = "en-us"
title = "Falcon Ridge Kansas"
theme = "hugo-community-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-117272854-1"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Falcon Ridge Kansas"
  description = "Falcon Ridge Kansas Community"
  # email = "your@email.com"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Falcon Ridge Kansas"
    # Optional logo stored in img/
    #logo = "logo.svg"
    resources = "Resources"
    amenities = "Amenities"
    about = "About"
    board = "Board"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    [[menu.prepend]]
      url = "http://sale.falconridgekansas.com"
      name = "Garage Sale"
      weight = 10

    # postpended links
    # [[menu.postpend]]
    #   url = "http://gohugo.io"
    #   name = "External link"
    #   weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Welcome To Our Community!"
    subtitle = "It's nice to meet you"
    buttonText = "Learn about us"


  # Resources section
  [params.resources]
    enable = true
    title = "Resources"
    subtitle = "Check out valuable resources you need to know."

    [[params.resources.row]]

    [[params.resources.row.list]]
      icon = "fa-file-pdf-o"
      title = "Declaration of Restrictions"
      description = "Falcon Ridge Declaration of Restrictions"
      url = "docs/fr-declaration.pdf"

    [[params.resources.row.list]]
      icon = "fa-file-pdf-o"
      title = "Declaration Amendments"
      description = "Falcon Ridge Declaration of Restrictions Amendments"
      url = "docs/fr-declaration-amendments.pdf"

    [[params.resources.row.list]]
      icon = "fa-file-pdf-o"
      title = "Estates Declaration of Restrictions"
      description = "Falcon Ridge Estates Declaration of Restrictions"
      url = "docs/fre-declaration.pdf"

    [[params.resources.row]]

    [[params.resources.row.list]]
      icon = "fa-file-pdf-o"
      title = "Estates Declaration Amendments"
      description = "Falcon Ridge Estates Declaration of Restrictions Amendments"
      url = "docs/fre-declaration-amendments.pdf"

    [[params.resources.row.list]]
      icon = "fa-file-pdf-o"
      title = "Bylaws"
      description = "These are the Bylaws currently posted by the Tiehen Group."
      url = "docs/bylaws.pdf"

    [[params.resources.row.list]]
      icon = "fa-file-pdf-o"
      title = "Architectural Approval Form"
      description = "Need to make some changes? Make sure you use this form to get the proper approvals and assistance on your journey."
      url = "docs/architectural-approval-form.pdf"

    [[params.resources.row]]

    [[params.resources.row.list]]
      icon = "fa-file-pdf-o"
      title = "Roofing Guidelines"
      description = "We have roofing guidelines to help create consistency throughout the community as well as to protect you from predatory companies looking to make a quick buck."
      url = "docs/roofing-guidelines.pdf"

    [[params.resources.row.list]]
      icon = "fa-slack"
      title = "Slack Group"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.resources.row.list]]
      icon = "fa-bolt"
      title = "Electricity/KCP&L"
      description = "Electricity is provided by Kansas City Power & Light. New/Stop service requests and bill payments may be done automatically on the website."
      url = "//www.kcpl.com/"

    [[params.resources.row]]

    [[params.resources.row.list]]
      icon = "fa-google"
      title = "Internet"
      description = "Our community has Google Fiber for your internet needs. We also have access to other providers"
      url = "//fiber.google.com/cities/kansascity/"

  # Amenities section
  [params.amenities]
    enable = true
    # All amenities defined in their own files. You can find example amenities
    # at 'exampleSite/data/amenities'. Copy the 'amenities' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Amenities"
    subtitle = "Lorem ipsum dolor sit amet consectetur."

    [params.amenities.modal]
      date = "Date"
      category = "Category"
      buttonText = "Close"


    # About section
  [params.about]
    enable = true
    title = "Meetings and Events Timeline"
    subtitle = "Here you can find information about future and past meetings including agendas and minutes. We'll also share events here."
    endpoint = "Be part<br>of our<br>story!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "meeting.png"
      date = "July 26th, 2018"
      title = "Board Meeting"
      description = "The agenda for this meeting has not been posted."

    [[params.about.events]]
      img = "meeting.png"
      date = "May 31st, 2018"
      title = "Board Meeting"
      description = "The agenda for this meeting has not been posted."

    [[params.about.events]]
      img = "annual-meeting.png"
      date = "April 26th, 2018"
      title = "Special Meeting of the Members"
      description = "The agenda for this meeting is available [here](docs/agenda-april-26-2018.pdf)."

    [[params.about.events]]
      img = "annual-meeting.png"
      date = "March 27th, 2018"
      title = "Annual Meeting"
      description = "The minutes are not yet available, but the [mailer](docs/2018-annual-meeting.pdf) is available for this meeting."

  # Board section
  [params.board]
    enable = true
    # Possibility to center items
    center = true
    title = "Board of Directors"
    subtitle = "We will strive for transparency by default."
    description = "The Board of Directors is elected by the HOA members. They represent the community as a whole and seek input from all involved. They also look to the future by creating a strategy for growth and maintenance"

    # All board member's pictures are stored under 'static/img/board'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.board.members]]
      img = "default.jpg"
      name = "Todd Stanley"
      position = "President"
      # reportsTo = "CTO"
      # livesIn = "[Munich, Germany](#some-maps-url)"
      # scope = [
      #   "UX for [member dashboard](#)",
      #   "Maintainer for [awesome-project](#)",
      #   "Open Source [community management](#)"
      # ]
      # For bio, markdown and even multiline strings are available.
      bio = """Todd is the President."""
      social = [
        #["fa-twitter", "#"],
        #["fa-facebook", "#"],
        #["fa-linkedin", "#"]
      ]

    [[params.board.members]]
      img = "default.jpg"
      name = "John Storey"
      position = "Vice President"
      bio = """John is the Vice President."""
      social = [
        #["fa-twitter", "#"],
        #["fa-facebook", "#"],
        #["fa-linkedin", "#"]
      ]

    [[params.board.members]]
      img = "default.jpg"
      name = "Kurt Doyle"
      position = "Secretary"
      bio = """Kurt is the Secretary."""
      social = [
        #["fa-twitter", "#"],
        #["fa-facebook", "#"],
        #["fa-linkedin", "#"]
      ]

    [[params.board.members]]
      img = "default.jpg"
      name = "Shawn Blume"
      position = "Treasurer"
      bio = """Shawn is the Treasurer. His wife, Natalee, and he have organized the wonderful holiday hayride for several years now. It's an event enjoyed by all."""
      social = [
        #["fa-twitter", "#"],
        #["fa-facebook", "#"],
        #["fa-linkedin", "#"]
      ]

    [[params.board.members]]
      img = "default.jpg"
      name = "Laura Barker"
      position = "Member"
      bio = """Laura brought back **Falcon Fest** the last two years, which has been a blast. She is striving to create a vibrant culture by highlighting our history and driving toward a shared future everyone can enjoy. Through this, she has found transparency is paramount to build trust within the community and ensure the board is focused on delivering value to homeowners."""
      social = [
        #["fa-twitter", "#"],
        #["fa-facebook", "#"],
        ["fa-linkedin", "https://www.linkedin.com/in/laura-sherman-barker-2b643a122/"],
        ["fa-envelope", "mailto:laura@falconridgekansas.com"]
      ]

  # Sponsor section
    [params.sponsors_list]
      # enable = true
      # Possibility to center items
      # center = true
      # Optional sponsor title specifying the involvement
      # title = "Used and trusted by"

      # All the sponsors' logos are stored under 'static/img/logos'.
      # Replace them with your sponsors' logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.sponsors]]
        logo = "envato.jpg"
        link = "#"

      [[params.sponsors]]
        logo = "designmodo.jpg"
        link = "#"

      [[params.sponsors]]
        logo = "themeforest.jpg"
        link = "#"

      [[params.sponsors]]
        logo = "creative-market.jpg"
        link = "#"

  # Contact section
  [params.contact]
    enable = true
    title = "Contact us"
    subtitle  = "We want to hear from you."
    buttonText = "Send message"
    # netlify = true

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "board@falconridgekansas.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for contacting us. Someone from the community will get back to you soon."
    #error = "Message could not be sent. Please contact us at mail@example.com instead."

    [params.contact.captcha]
      # sitekey = ""

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."

    # [[params.footer.social]]
    #   icon = "fa-twitter"
    #   link = "#"
    #   title = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "https://www.facebook.com/falconridgekansas/"
      title = "Facebook"

    # [[params.footer.social]]
    #   icon = "fa-linkedin"
    #   link = "#"
    #   title = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
